### ISSUE TITLE
Surge XT Plugins Cannot Load Skins, Browse Patches

### ISSUE THREAD

**Issue by takuvata** [flathub/org.surge_synth_team.surge-xt#1] opened 2022-07-29 08:39 UTC
LV2 and VST3 plugins (org.freedesktop.LinuxAudio.Plugins.Surge-XT package) cannot load skins and patches. Loads with "In Memory Default (parse error)" skin and does not show any others. Also does not show any patches in the patch browser. Standalone version works correctly. Plugins were working correctly some time ago.

**Comment by takuvata** [comment] 2022-07-29 08:57
Built and installed the flatpak from the now archived repo at https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Surge-XT.git and that one works fine.

**Comment by baconpaul** [comment] 2022-07-29 11:23
Curious what the about screen shows? This will happen if the /usr/share/Surge XT directory is middling or mis configured. 

Full disclosure: I’ve never used flstpak so can’t debug beyond that insight. But from my understanding of it it sounds like the plugin runs in an environment which isn’t finding those shared resources either because they are renamed or not included.

**Comment by hfiguiere** [comment] 2022-07-29 12:44
There is no `/usr/share/Surge XT` (`/usr` is read-only at build time, that's what prefixes are for) - but I tried to make sure the path where working. I test that the thing worked though, so if you give better "step by step" I'll be able to better reproduce.

Also in which DAW? Things worked from in Ardour (Flatpak version)

**Comment by takuvata** [comment] 2022-07-29 13:33
DAW - all of them: lmms, ardour, bitwig, same behaviour. Plugin technically works and is functional just it doesn't let you browse factory patches and runs with in memory default skin.

In Menu -> About Surge, working old package says "Factory Data: /app/extensions/Plugins/Surge-XT/share/surge-xt", broken package currently in flathub says: "Factory Data: /usr/share/Surge XT".

Also current package in about screen says: "Current Skin: In Memory Fallback Skin"

When you go to Menu -> Skins it tells "In Memory Default (parse error)" and does not allow to choose anything else. In working package it lets you choose between "Surge Classic" and "Surge Black".

When you click in the patch browser area at the top of the UI current package does not show any factory patches. Old package lets you browse factory patches.

**Comment by hfiguiere** [comment] 2022-07-30 15:58
ok I totally messed up the path when building moving to a standalone + plugin build (I seem to have only tested the standalone at that point)

Working on a fix.

Sorry about that.

**Comment by baconpaul** [comment] 2022-07-30 16:25
Thanks for doing this!!!

**Comment by hfiguiere** [comment] 2022-07-30 16:41
Just to summarize:
- Surge XT uses the prefix to determine the default location.
- I did built the VST3 out of the same prefix as the standalone, and that won't work due to the way plugins work with flatpak
- Made the mistake to use an env variable for the LV2 that is build separately so the prefix was wrong too.
- Didn't test the plugins properly.

The solution:
- Build the VST3 separately
- Set the prefix properly on the LV2 (also built separately due to JUCE-lv2)

And it works like it used to be.

**Comment by takuvata** [comment] 2022-07-30 17:43
Indeed - thank you very much for doing this!

**Closed as completed** 2022-07-30 17:46 UTC
